### ISSUE TITLE
Get rid of pycountry

### ISSUE THREAD

**Issue by pudo** [occrp/countrynames#10]
Hey @rgieseke, I'm having some issues with pycountry, in particular the fact that it's missing countries (like Kosovo) and has given up on iso-639-1 codes for languages. Replacing it from this library would be relatively simple, were it not for all the aliasing functions (to_name, to_official_name, to_numeric) which are dependent on the full pycountry dataset. Are you using this? Would you be able to top out the version of countrynames in the places where you depend on it so that newer versions can get rid of the dependency?

**Comment by rgieseke** [comment]
Had thought about proposing this as well!

I do use the three-letter codes but for country names I actually use https://github.com/rgieseke/shortcountrynames - in plot labelling or for selection boxes.

I'll try to submit a pull request - would you be fine with including only the two and three letter functions?

**Comment by rgieseke** [comment]
WIP here: https://github.com/occrp/countrynames/tree/remove-pycountry

**Comment by BradKML** [comment]
This sounds interesting....
