### ISSUE TITLE
pyicu dependency

### ISSUE THREAD

**Issue by rgieseke** [occrp/countrynames#15]
`countrynames` depends on `normality` which as of version 1 depends on `pyicu` -
`pyicu` can be hard to install, so a workaround might be to pin to a pre-1.0 version of `normality`

See discussion in 
https://github.com/pudo/normality/issues/6

**Comment by pudo** [comment]
Hm, that would make it unusable for all the use cases in @alephdata ...

**Comment by rgieseke** [comment]
Yeah, i mostly wanted to keep a note for others (i.e. me helping a colleague) to workaround the issue ...
or one of the fixes discussed in the issue above.

Sorry for wording this poorly.
