### ISSUE TITLE
Sark

### ISSUE THREAD

**Issue by rgieseke** [occrp/countrynames#25]
Sark is included in FAIL as well as in GG (Guernsey)

It was introduced in https://github.com/alephdata/countrynames/commit/01caa4e4114fb7392b5a738afde259292327ad8c

Should we remove that from FAIL @gsime1 ?

**Comment by gabrielesimeone** [comment]
Hey, thanks for spotting this. Yes it should be removed from FAIL, as GG does include Sark island. see: https://www.iso.org/obp/ui/#iso:code:3166:GG

**Comment by rgieseke** [comment]
Thanks for the quick reply! Will remove it then ....
