### ISSUE TITLE
Release of current version

### ISSUE THREAD

**Issue by radwo** [occrp/countrynames#26]
@rgieseke Can you release the current version of `countrynames`? There are some additions to the list, and I would like to use them in https://github.com/pudo/opensanctions

I have no idea how `pip` works, but I think that this is the only way to use the newest code?

**Comment by rgieseke** [comment]
Will check doing a release later, installing from GitHub should also work:
```
pip install git+https://github.com/alephdata/countrynames.git
```

**Comment by pudo** [comment]
Done :) I've also linked the releases to CI so you only need to do `bump2version patch` from now on to do releases, then push the tag.
