### ISSUE TITLE
python yaml is slow

### ISSUE THREAD

**Issue by enodr** [occrp/countrynames#31]
Python yaml loader is way slower than the json loader.

Replacing data.yaml file with a json file would speed up considerably the loading time of this library (several seconds on a modern computer).

**Comment by pudo** [comment]
The startup time really is an issue, but using YAML is just very convenient in terms of editing the `data.yaml` easily. One thought I had was to have a build time script to make a Python module from it, which would probably be optimal in terms of loading time. WDYT, too messy?

**Comment by rgieseke** [comment]
I used the approach of creating Python modules from YAML or CSV in a few projects, i think it's the best if there is some automatic checking that it's not out-of-date (e.g. GitHub action).

**Comment by enodr** [comment]
> The startup time really is an issue, but using YAML is just very convenient in terms of editing the `data.yaml` easily. One thought I had was to have a build time script to make a Python module from it, which would probably be optimal in terms of loading time. WDYT, too messy?

That's kind of what I had in mind. Keep the YAML file for readability / debug, but use a script to (re)generate a module. Just build upon gen.py that you use to generate the YAML file.

**Comment by pudo** [comment]
This is implemented in `master` now. Anyone want to give it a shake before I cut a release?

**Comment by rgieseke** [comment]
Works for me :-)

See #32

**Comment by enodr** [comment]
According to CProfile loading time is cut down from ~4s to <1s on my setup. 

Edit: after looking at the trace, I realize 95% of the time is spent in process_data -> normalize_name; Why not just storing data.py with already normalized names, or just pickle/unpickle ? Let me do some more testing and maybe come up with a PR.

**Comment by pudo** [comment]
Basically, because what `normalize_name` does is a bit dependent on where you run it. If you don't have pyicu installed it'll be super rough, but even with ICU installed it varies wildly: the Linux version installed on GitHub runners, for example, doesn't support Burmese very well, while the version shipped with homebrew on OS X does it well.

That variation is still sort of survivable, but it means the lookup tables really should be built with the same mechanism as the lookups...

**Comment by enodr** [comment]
Indeed I understand we depend of the host target. Then why not generating the normalized data file from setup.py (edit: I am not that familiar with pip modules but I guess it calls setup.py)?

With a non normalized data file:
![image](https://user-images.githubusercontent.com/10436257/165490024-77bcdb70-903a-4ccc-afd7-f02c1b398eb2.png)

By simply loading a normalized json file (90x speed gain):
![image](https://user-images.githubusercontent.com/10436257/165490251-5b67fea5-7534-41b4-a737-12e164d995c9.png)

**Comment by pudo** [comment]
If you can figure out how to put it into a post-install hook via setup.py/pip, I'd definitely take that PR!

**Comment by enodr** [comment]
PR created https://github.com/alephdata/countrynames/pull/33

post installs scripts are not supported with pip wheel packages, thus this patch simply allows a user to manually create an optimized cached version on his system. CProfile won't even capture the trace as the execution is too fast.

**Comment by pudo** [comment]
This has been addressed to the extent I think is useful, note also #33 for some rejected further optimisations.
