### ISSUE TITLE
Improve fuzzy matching

### ISSUE THREAD

**Issue by rgieseke** [occrp/countrynames#8]
@pudo I've committed a fix for typoed islands (like "Falklands Islands") not having a chance in fuzzy matching against "Island" (leading to a longer than one list of matches). I think there are further improvements possible, like a Levenshtein matching that stops computing after the distance is too long or checking each group for matches instead of all from one country to speed up fuzzy matching.

I've also changed the test script to use py.test, I hope that's fine with you.

**Comment by pudo** [comment]
I think this is all long since merged, no?

**Comment by rgieseke** [comment]
Yeah, https://github.com/alephdata/countrynames/commit/9379e578340394cbb3ef10b1ba5d0468003bc265

Further improvements certainly possible, but the specific was fixed i think.
