### ISSUE TITLE
How to deal with dissolved countries?

### ISSUE THREAD

**Issue by rgieseke** [occrp/countrynames#9]
What is the policy for countries not existing anymore? For example the "Netherland Antilles" (https://en.wikipedia.org/wiki/Dissolution_of_the_Netherlands_Antilles) - one could as currently assign it to the BES islands but I think it would make more sense to assign the old code.

Thoughts?

**Comment by pudo** [comment]
I would totally allow for them, we already have "Yugoslavia", "Serbia and Montenegro", "Soviet Union". Code-wise, some old countries have four-letter codes now, otherwise let's just use their old codes and hope they don't get re-used :)

**Comment by rgieseke** [comment]
Ok, I'll try to move out the Netherlands Antilles with their 4-letter code.

https://en.wikipedia.org/wiki/ISO_3166-3#Current_codes

**Comment by rgieseke** [comment]
Problem was that both Netherlands and the BES islands had entries for the Antilles making the matching not so deterministic I guess ...
